/**
 * Hand-made art overrides. Every sprite is still generated by code; this is
 * the one place a drawn image may replace a generated one. A file under
 * `public/art/` is optional: when it exists it is loaded once at start-up and
 * used instead of the drawing, when it is missing the code-drawn art stays.
 * Images are used at their own pixel size, never scaled by a fraction.
 */

/** Item base ids that may have an icon at `art/items/<id>.png` (any size, transparent background; see `public/art/README.md`). */
export const ITEM_ART_IDS = ['sword', 'bow', 'dagger', 'mace', 'crossbow', 'skull', 'quiver', 'lantern', 'energy_shield', 'belt', 'wooden_shield_base', 'iron_shield', 'tower_shield', 'leather_armor', 'helmet', 'amulet', 'ring', 'war_belt', 'gauntlets', 'spear', 'chest_armor', 'boots', 'blowgun', 'spellbook', 'bardiche', 'javelin', 'warfork', 'wand', 'staff', 'pilgrim_cap', 'pilgrim_boots', 'vital_charm', 'axe', 'prisoner_cuffs', 'prisoner_ball'];
/** Bases that share another base's drawing: the starters look like the plain weapon they are. */
const ITEM_ART_ALIASES: Record<string, string> = { wooden_sword: 'sword', wooden_bow: 'bow', starter_dagger: 'dagger', starter_spear: 'spear', wooden_staff: 'staff', wooden_shield: 'wooden_shield_base', power_ring: 'ring', weak_amulet: 'amulet', jade_amulet: 'amulet', pilgrim_coat: 'leather_armor' };


const itemImages = new Map<string, HTMLCanvasElement>();

/** Fetches every optional image before play. Missing files are skipped quietly. */
export async function loadArt(): Promise<void> {
  if (typeof document === 'undefined') return;
  await Promise.all(ITEM_ART_IDS.map((id) => loadItemImage(id)));
}

async function loadItemImage(id: string): Promise<void> {
  const url = `${import.meta.env.BASE_URL}art/items/${id}.png`;
  const img = new Image();
  const ok = await new Promise<boolean>((resolve) => {
    img.onload = () => resolve(true);
    img.onerror = () => resolve(false);
    img.src = url;
  });
  if (!ok || !img.naturalWidth) return;
  // Copied into a canvas so it draws like the generated icons, crisp and unsmoothed
  const c = document.createElement('canvas');
  c.width = img.naturalWidth;
  c.height = img.naturalHeight;
  const ctx = c.getContext('2d')!;
  ctx.imageSmoothingEnabled = false;
  ctx.drawImage(img, 0, 0);
  // The drawing is kept at its own pixel size, transparent margins trimmed, so a slot can fit the drawing itself
  itemImages.set(id, trim(c));
}

/** Cuts the transparent margins off an image; a fully transparent image is kept as it is. */
function trim(src: HTMLCanvasElement): HTMLCanvasElement {
  const px = src.getContext('2d')!.getImageData(0, 0, src.width, src.height).data;
  let x0 = src.width;
  let y0 = src.height;
  let x1 = -1;
  let y1 = -1;
  for (let y = 0; y < src.height; y++) {
    for (let x = 0; x < src.width; x++) {
      if (px[(y * src.width + x) * 4 + 3]! === 0) continue;
      if (x < x0) x0 = x;
      if (x > x1) x1 = x;
      if (y < y0) y0 = y;
      if (y > y1) y1 = y;
    }
  }
  if (x1 < 0 || (x0 === 0 && y0 === 0 && x1 === src.width - 1 && y1 === src.height - 1)) return src;
  const out = document.createElement('canvas');
  out.width = x1 - x0 + 1;
  out.height = y1 - y0 + 1;
  out.getContext('2d')!.drawImage(src, x0, y0, out.width, out.height, 0, 0, out.width, out.height);
  return out;
}

const shrunkCache = new WeakMap<HTMLCanvasElement, Map<number, HTMLCanvasElement>>();

/** The sprite shrunk by a whole factor, made once and kept, for slots too small to show it at its own size. */
export function shrunk(src: HTMLCanvasElement, k: number): HTMLCanvasElement {
  let byK = shrunkCache.get(src);
  if (!byK) {
    byK = new Map();
    shrunkCache.set(src, byK);
  }
  let out = byK.get(k);
  if (!out) {
    out = shrink(src, k);
    byK.set(k, out);
  }
  return out;
}

/**
 * Shrinks an icon by a whole factor: each output pixel is the alpha-weighted
 * average of its block, and the alpha is snapped to on or off so the result
 * has hard pixel edges like the generated icons. Never done per frame.
 */
function shrink(src: HTMLCanvasElement, k: number): HTMLCanvasElement {
  const w = Math.ceil(src.width / k);
  const h = Math.ceil(src.height / k);
  const px = src.getContext('2d')!.getImageData(0, 0, src.width, src.height).data;
  const out = document.createElement('canvas');
  out.width = w;
  out.height = h;
  const ctx = out.getContext('2d')!;
  const id = ctx.createImageData(w, h);
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      let r = 0;
      let g = 0;
      let b = 0;
      let wa = 0;
      let a = 0;
      for (let yy = 0; yy < k; yy++) {
        for (let xx = 0; xx < k; xx++) {
          const sx = x * k + xx;
          const sy = y * k + yy;
          if (sx >= src.width || sy >= src.height) continue;
          const i = (sy * src.width + sx) * 4;
          const al = px[i + 3]! / 255;
          r += px[i]! * al;
          g += px[i + 1]! * al;
          b += px[i + 2]! * al;
          wa += al;
          a += px[i + 3]!;
        }
      }
      const o = (y * w + x) * 4;
      if (wa > 0) {
        id.data[o] = r / wa;
        id.data[o + 1] = g / wa;
        id.data[o + 2] = b / wa;
      }
      id.data[o + 3] = a / (k * k) >= 128 ? 255 : 0;
    }
  }
  ctx.putImageData(id, 0, 0);
  return out;
}

/** The drawn icon for an item base, or null to use the generated one. */
export function itemImage(baseId: string): HTMLCanvasElement | null {
  return itemImages.get(ITEM_ART_ALIASES[baseId] ?? baseId) ?? null;
}
