/**
 * Hand-made art overrides. Every sprite is still generated by code; this is
 * the one place a drawn image may replace a generated one. A file under
 * `public/art/` is optional: when it exists it is loaded once at start-up and
 * used instead of the drawing, when it is missing the code-drawn art stays.
 * Images are used at their own pixel size, never scaled by a fraction.
 */

import type { ClassId } from '../data/classes';
import type { AnimSet, CharacterSheet } from '../gen/pixel/characters';
import type { SpriteAnim } from '../gen/pixel/sprites';

/** Item base ids that may have an icon at `art/items/<id>.png` (any size, transparent background; see `public/art/README.md`). */
export const ITEM_ART_IDS = ['sword', 'bow', 'dagger', 'mace', 'crossbow', 'skull', 'quiver', 'lantern', 'energy_shield', 'belt', 'wooden_shield_base', 'iron_shield', 'tower_shield', 'leather_armor', 'helmet', 'amulet', 'ring', 'war_belt', 'gauntlets', 'spear', 'chest_armor', 'boots', 'blowgun', 'spellbook', 'bardiche', 'javelin', 'warfork', 'wand', 'staff', 'pilgrim_cap', 'pilgrim_boots', 'vital_charm', 'axe', 'prisoner_cuffs', 'prisoner_ball', 'pilgrim_gloves'];
/** Bases that share another base's drawing: the starters look like the plain weapon they are. */
const ITEM_ART_ALIASES: Record<string, string> = { wooden_sword: 'sword', wooden_bow: 'bow', starter_dagger: 'dagger', starter_spear: 'spear', wooden_staff: 'staff', wooden_shield: 'wooden_shield_base', power_ring: 'ring', weak_amulet: 'amulet', jade_amulet: 'amulet', pilgrim_coat: 'leather_armor' };


const itemImages = new Map<string, HTMLCanvasElement>();

/**
 * Classes drawn from hand-made sprites instead of the generated hero, when
 * their files exist at `art/heroes/<classId>/<anim>_<dir>.png`: `anim` is
 * idle, walk or attack, `dir` is n, s, e or w, and more frames of one
 * animation follow as `_2`, `_3`... (see `public/art/README.md`). The idle
 * set needs all four directions; walk and attack are used direction by
 * direction as their frames arrive, each missing direction falling back to
 * that direction's idle.
 */
export const HERO_ART_CLASSES: ClassId[] = ['sorcerer2'];
/** Classes whose sprites are shrunk by a whole factor at load (block averages, hard edges). None today: Sorcerer2's witch is drawn at 32 by 32 to begin with (2026-10-03). */
export const HERO_ART_SHRINK: Partial<Record<ClassId, number>> = {};
export type HeroDir = 'n' | 's' | 'e' | 'w';
export type HeroAnimName = 'idle' | 'walk' | 'attack';
export type HeroArtSet = Record<HeroDir, HTMLCanvasElement[]>;
export interface HeroArt {
  idle: HeroArtSet;
  /** Walk and attack frames per direction; a direction without any uses its idle frames. */
  walk: Partial<HeroArtSet>;
  attack: Partial<HeroArtSet>;
}
const HERO_DIRS: HeroDir[] = ['n', 's', 'e', 'w'];
const MAX_FRAMES = 12;

const heroImages = new Map<string, HeroArt>();

/** The training dummies' hand-made sprite: `art/dummies/dummy.png` for all of them, or `art/dummies/<id>.png` for one kind (fire, cold, lightning, poison, physical). One still image, drawn the same from every side. */
const dummyImages = new Map<string, HTMLCanvasElement>();
const DUMMY_IDS = ['fire', 'cold', 'lightning', 'poison', 'physical'];

/** Town furniture with a hand-made sprite at `art/props/<id>.png`, more frames of an animated piece numbered `_2`, `_3`...: the stash chest, the pair of chests beside the merchant, and the portal (town portal and return portal alike). */
export const PROP_ART_IDS = ['stash', 'merchant_chest', 'portal'];
const propImages = new Map<string, HTMLCanvasElement[]>();

/** Townsfolk with a hand-made sprite at `art/npcs/<id>.png`: one still image each. The merchant today. */
export const NPC_ART_IDS = ['merchant'];
const npcImages = new Map<string, HTMLCanvasElement>();

/** Fetches every optional image before play. Missing files are skipped quietly. */
export async function loadArt(): Promise<void> {
  if (typeof document === 'undefined') return;
  await Promise.all([...ITEM_ART_IDS.map((id) => loadItemImage(id)), ...HERO_ART_CLASSES.map((id) => loadHeroArt(id)), ...['dummy', ...DUMMY_IDS].map((id) => loadDummyImage(id)), ...NPC_ART_IDS.map((id) => loadNpcImage(id)), ...PROP_ART_IDS.map((id) => loadPropImage(id))]);
}

async function loadPropImage(id: string): Promise<void> {
  const frames: HTMLCanvasElement[] = [];
  for (let n = 1; n <= MAX_FRAMES; n++) {
    const c = await fetchImage(`${import.meta.env.BASE_URL}art/props/${id}${n === 1 ? '' : `_${n}`}.png`);
    if (!c) break;
    frames.push(c);
  }
  if (frames.length) propImages.set(id, frames);
}

/** The frames for a piece of town furniture, or null for the code-drawn one. */
export function propArt(id: string): HTMLCanvasElement[] | null {
  return propImages.get(id) ?? null;
}

/** Hand-made frames as a prop animation standing on its lowest drawn pixel: a still at one frame, otherwise `frameTime` seconds a frame. */
export function propAnim(frames: HTMLCanvasElement[], frameTime = 0.12): SpriteAnim {
  return artAnim(frames, frames.length > 1 ? frameTime : 1);
}

async function loadNpcImage(id: string): Promise<void> {
  const c = await fetchImage(`${import.meta.env.BASE_URL}art/npcs/${id}.png`);
  if (c) npcImages.set(id, c);
}

/** The sprite for a townsperson, or null for the code-drawn one. */
export function npcArt(id: string): HTMLCanvasElement | null {
  return npcImages.get(id) ?? null;
}

async function loadDummyImage(id: string): Promise<void> {
  const c = await fetchImage(`${import.meta.env.BASE_URL}art/dummies/${id}.png`);
  if (c) dummyImages.set(id, c);
}

/** The sprite for a training dummy kind: its own file, else the shared one, else null for the code-drawn dummy. */
export function dummyArt(id: string): HTMLCanvasElement | null {
  return dummyImages.get(id) ?? dummyImages.get('dummy') ?? null;
}

/** A sheet from one still drawing: the same frame for every facing and animation, feet at the bottom centre. */
export function stillSheet(frame: HTMLCanvasElement): CharacterSheet {
  const anim = artAnim([frame], 1);
  const set: AnimSet = { idle: anim, walk: anim, attack: anim };
  return { front: set, back: set, side: set, height: frame.height };
}

/** One image as a crisp canvas, or null when the file is not there. */
async function fetchImage(url: string): Promise<HTMLCanvasElement | null> {
  const img = new Image();
  const ok = await new Promise<boolean>((resolve) => {
    img.onload = () => resolve(true);
    img.onerror = () => resolve(false);
    img.src = url;
  });
  if (!ok || !img.naturalWidth) return null;
  const c = document.createElement('canvas');
  c.width = img.naturalWidth;
  c.height = img.naturalHeight;
  const ctx = c.getContext('2d')!;
  ctx.imageSmoothingEnabled = false;
  ctx.drawImage(img, 0, 0);
  return c;
}

/** The frames of one animation facing one way: `<anim>_<dir>.png`, then `_2`, `_3`... while they exist. Kept at their own size, untrimmed, so every frame shares the artist's framing. */
async function loadHeroFrames(classId: string, anim: HeroAnimName, dir: HeroDir): Promise<HTMLCanvasElement[]> {
  const frames: HTMLCanvasElement[] = [];
  for (let n = 1; n <= MAX_FRAMES; n++) {
    const frame = await fetchImage(`${import.meta.env.BASE_URL}art/heroes/${classId}/${anim}_${dir}${n === 1 ? '' : `_${n}`}.png`);
    if (!frame) break;
    const k = HERO_ART_SHRINK[classId as ClassId] ?? 1;
    frames.push(k > 1 ? shrunk(frame, k) : frame);
  }
  return frames;
}

async function loadHeroArt(classId: string): Promise<void> {
  const load = async (anim: HeroAnimName): Promise<Partial<HeroArtSet>> => {
    const dirs = await Promise.all(HERO_DIRS.map((dir) => loadHeroFrames(classId, anim, dir)));
    const set: Partial<HeroArtSet> = {};
    HERO_DIRS.forEach((dir, i) => { if (dirs[i]!.length) set[dir] = dirs[i]; });
    return set;
  };
  const idle = await load('idle');
  if (!HERO_DIRS.every((dir) => idle[dir])) return;
  heroImages.set(classId, { idle: idle as HeroArtSet, walk: await load('walk'), attack: await load('attack') });
}

/** The hand-made sprites for a class, when its idle set is complete. */
export function heroArt(classId: string): HeroArt | null {
  return heroImages.get(classId) ?? null;
}

/** Rows of empty canvas under the lowest drawn pixel of a frame. */
function bottomMargin(frame: HTMLCanvasElement): number {
  const px = frame.getContext('2d')!.getImageData(0, 0, frame.width, frame.height).data;
  for (let y = frame.height - 1; y >= 0; y--) {
    for (let x = 0; x < frame.width; x++) if (px[(y * frame.width + x) * 4 + 3]! > 0) return frame.height - 1 - y;
  }
  return 0;
}

const marginCache = new WeakMap<HTMLCanvasElement, number>();

/**
 * One animation from hand-made frames. The feet are placed on the ground at
 * the lowest drawn pixel across the frames, not the canvas edge, so empty
 * canvas under a drawing never floats it, while the bob from one frame to
 * the next is kept.
 */
function artAnim(frames: HTMLCanvasElement[], frameTime: number): SpriteAnim {
  let margin = Infinity;
  for (const f of frames) {
    let m = marginCache.get(f);
    if (m === undefined) {
      m = bottomMargin(f);
      marginCache.set(f, m);
    }
    margin = Math.min(margin, m);
  }
  return { frames, originX: frames[0]!.width >> 1, originY: frames[0]!.height - (Number.isFinite(margin) ? margin : 0), frameTime };
}

/**
 * A character sheet built from hand-made sprites: south faces the camera
 * (front), north is the back, east the side and west its own set, so the
 * renderer never mirrors the artist's drawing. Feet sit at the bottom centre
 * of the drawing; idle frames change every quarter second, walk and attack
 * every eighth.
 */
export function heroArtSheet(art: HeroArt): CharacterSheet {
  const anim = artAnim;
  const set = (dir: HeroDir): AnimSet => ({
    idle: anim(art.idle[dir], 0.25),
    walk: anim(art.walk[dir] ?? art.idle[dir], 0.125),
    attack: anim(art.attack[dir] ?? art.idle[dir], 0.125),
  });
  return { front: set('s'), back: set('n'), side: set('e'), left: set('w'), height: art.idle.s[0]!.height };
}

async function loadItemImage(id: string): Promise<void> {
  // Copied into a canvas so it draws like the generated icons, crisp and unsmoothed
  const c = await fetchImage(`${import.meta.env.BASE_URL}art/items/${id}.png`);
  if (!c) return;
  // The drawing is kept at its own pixel size, transparent margins trimmed, so a slot can fit the drawing itself
  itemImages.set(id, trim(c));
}

/** Cuts the transparent margins off an image; a fully transparent image is kept as it is. */
function trim(src: HTMLCanvasElement): HTMLCanvasElement {
  const px = src.getContext('2d')!.getImageData(0, 0, src.width, src.height).data;
  let x0 = src.width;
  let y0 = src.height;
  let x1 = -1;
  let y1 = -1;
  for (let y = 0; y < src.height; y++) {
    for (let x = 0; x < src.width; x++) {
      if (px[(y * src.width + x) * 4 + 3]! === 0) continue;
      if (x < x0) x0 = x;
      if (x > x1) x1 = x;
      if (y < y0) y0 = y;
      if (y > y1) y1 = y;
    }
  }
  if (x1 < 0 || (x0 === 0 && y0 === 0 && x1 === src.width - 1 && y1 === src.height - 1)) return src;
  const out = document.createElement('canvas');
  out.width = x1 - x0 + 1;
  out.height = y1 - y0 + 1;
  out.getContext('2d')!.drawImage(src, x0, y0, out.width, out.height, 0, 0, out.width, out.height);
  return out;
}

const shrunkCache = new WeakMap<HTMLCanvasElement, Map<number, HTMLCanvasElement>>();

/** The sprite shrunk by a whole factor, made once and kept, for slots too small to show it at its own size. */
export function shrunk(src: HTMLCanvasElement, k: number): HTMLCanvasElement {
  let byK = shrunkCache.get(src);
  if (!byK) {
    byK = new Map();
    shrunkCache.set(src, byK);
  }
  let out = byK.get(k);
  if (!out) {
    out = shrink(src, k);
    byK.set(k, out);
  }
  return out;
}

/**
 * Shrinks an icon by a whole factor: each output pixel is the alpha-weighted
 * average of its block, and the alpha is snapped to on or off so the result
 * has hard pixel edges like the generated icons. Never done per frame.
 */
function shrink(src: HTMLCanvasElement, k: number): HTMLCanvasElement {
  const w = Math.ceil(src.width / k);
  const h = Math.ceil(src.height / k);
  const px = src.getContext('2d')!.getImageData(0, 0, src.width, src.height).data;
  const out = document.createElement('canvas');
  out.width = w;
  out.height = h;
  const ctx = out.getContext('2d')!;
  const id = ctx.createImageData(w, h);
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      let r = 0;
      let g = 0;
      let b = 0;
      let wa = 0;
      let a = 0;
      for (let yy = 0; yy < k; yy++) {
        for (let xx = 0; xx < k; xx++) {
          const sx = x * k + xx;
          const sy = y * k + yy;
          if (sx >= src.width || sy >= src.height) continue;
          const i = (sy * src.width + sx) * 4;
          const al = px[i + 3]! / 255;
          r += px[i]! * al;
          g += px[i + 1]! * al;
          b += px[i + 2]! * al;
          wa += al;
          a += px[i + 3]!;
        }
      }
      const o = (y * w + x) * 4;
      if (wa > 0) {
        id.data[o] = r / wa;
        id.data[o + 1] = g / wa;
        id.data[o + 2] = b / wa;
      }
      id.data[o + 3] = a / (k * k) >= 128 ? 255 : 0;
    }
  }
  ctx.putImageData(id, 0, 0);
  return out;
}

/** The drawn icon for an item base, or null to use the generated one. */
export function itemImage(baseId: string): HTMLCanvasElement | null {
  return itemImages.get(ITEM_ART_ALIASES[baseId] ?? baseId) ?? null;
}
