import { CLASSES, CLASS_LIST, LEVELING, type ClassId } from '../../data/classes';
import { pledgesFor } from '../../data/pledges';
import { SKILLS } from '../../data/skills';
import { button, clear, h, hex } from '../dom';

export interface ScreenHost {
  newGame(): void;
  continueGame(): void;
  showcase(): void;
  lab(): void;
  chooseClass(id: ClassId): void;
  choosePledge(classId: ClassId, id: string): void;
  respawn(): void;
  cancelToTitle(): void;
}

/** Full-screen states: title, class pick, pledge pick, death. */
export class Screens {
  readonly root: HTMLDivElement;
  hasSave = false;
  installHint: string | null = null;

  constructor(parent: HTMLElement, private readonly host: ScreenHost) {
    this.root = h('div', { class: 'screen' });
    this.root.addEventListener('pointerdown', (e) => e.stopPropagation());
    parent.appendChild(this.root);
  }

  hide(): void {
    this.root.style.display = 'none';
    clear(this.root);
  }

  private show(...children: (HTMLElement | null)[]): void {
    clear(this.root);
    this.root.style.display = 'flex';
    this.root.append(...children.filter((c): c is HTMLElement => !!c));
  }

  splash(): void {
    this.show(
      h('div', { class: 'title-block' }, h('div', { class: 'title-small' }, 'A grim action RPG, all art generated by code'), h('h1', { class: 'title' }, 'Falling Sky')),
      h(
        'div',
        { class: 'title-buttons' },
        this.hasSave ? button('Continue', () => this.host.continueGame(), 'btn big primary') : null,
        button(this.hasSave ? 'New Hero' : 'Play', () => this.host.newGame(), 'btn big' + (this.hasSave ? '' : ' primary')),
        button('Visual Showcase', () => this.host.showcase(), 'btn'),
        button('Art Lab (desktop)', () => this.host.lab(), 'btn'),
      ),
      h('div', { class: 'title-note' }, 'Monsters and the Proving Grounds are placeholders until the real monster and zone data arrives.'),
      this.installHint ? h('div', { class: 'title-note install' }, this.installHint) : null,
    );
  }

  classSelect(): void {
    const cards = CLASS_LIST.map((c) =>
      h(
        'div',
        { class: 'card', style: `--c:${hex(c.color)}` },
        h('div', { class: 'card-title' }, c.name),
        h('div', { class: 'card-text' }, c.description),
        h('div', { class: 'card-stats' }, `STR ${c.base.str}  DEX ${c.base.dex}  INT ${c.base.int}  VIT ${c.base.vit}`),
        h('div', { class: 'card-stats dim' }, `Per level: +${c.perLevel.str} STR, +${c.perLevel.dex} DEX, +${c.perLevel.int} INT, +${c.perLevel.vit} VIT`),
        button('Choose ' + c.name, () => this.host.chooseClass(c.id), 'btn primary'),
      ),
    );
    this.show(h('h2', { class: 'screen-title' }, 'Choose your class'), h('div', { class: 'cards' }, ...cards), button('Back', () => this.host.cancelToTitle(), 'btn ghost'));
  }

  /** `forced`: the level-20 choice during play, with no way back. */
  pledgeSelect(classId: ClassId, forced = false): void {
    const cls = CLASSES[classId];
    const cards = pledgesFor(classId).map((p) =>
      h(
        'div',
        { class: 'card', style: `--c:${hex(p.color)}` },
        h('div', { class: 'card-title' }, p.name),
        h('div', { class: 'card-sub' }, p.title),
        h('div', { class: 'card-text' }, p.description),
        h('div', { class: 'card-stats dim' }, 'Skills: ' + p.skills.map((s) => SKILLS[s]?.name ?? s).join(', ')),
        button('Pledge to ' + p.name, () => this.host.choosePledge(classId, p.id), 'btn primary'),
      ),
    );
    this.show(
      h('h2', { class: 'screen-title' }, forced ? `Level ${LEVELING.pledgeLevel}: ${cls.name}, swear your pledge` : `${cls.name}: choose a pledge`),
      forced ? h('div', { class: 'title-note' }, 'The world waits. Nothing can hurt you until you choose, and you cannot move.') : null,
      h('div', { class: 'cards' }, ...cards),
      forced ? null : button('Back', () => this.host.cancelToTitle(), 'btn ghost'),
    );
  }

  dead(): void {
    this.root.classList.add('dead');
    this.show(h('h1', { class: 'title death' }, 'You died'), h('div', { class: 'title-note' }, 'No penalty. Your gear and gold are safe.'), button('Return to town', () => this.host.respawn(), 'btn big primary'));
  }

  clearDead(): void {
    this.root.classList.remove('dead');
  }
}
