import { Color, Vector3 } from 'three';
import { ALL_RECIPES, HERO_RECIPES, MONSTER_RECIPES, type CharacterRecipe } from '../gen/characters';
import { Rng } from '../gen/rng';
import { Clip, type ClipId } from '../render/characterMaterial';
import { Actor, Crowd } from '../render/crowd';
import { Effects } from '../render/effects';
import { ParticleSystem } from '../render/particles';
import { Stage } from '../render/stage';
import { Panel, el } from '../ui/panel';

type Vec3 = [number, number, number];

const HORDE_SIZE = 200;
const GALLERY_SPACING = 3.15;

interface Timer {
  at: number;
  fn: () => void;
}

/**
 * The visual showcase: a gallery of generated characters on a stage, animation
 * buttons, spells cast at the monsters, and an optional 200-monster horde.
 */
export class Showcase {
  readonly stage: Stage;
  readonly particles: ParticleSystem;
  readonly effects: Effects;
  readonly crowds = new Map<string, Crowd>();
  readonly gallery: Actor[] = [];
  private readonly hero: Actor;
  private readonly monsters: Actor[] = [];
  private readonly horde: { actor: Actor; heading: number; speed: number }[] = [];
  private hordeOn = false;
  private turntable = false;
  private focus = -1;
  private time = 0;
  private readonly timers: Timer[] = [];
  private readonly rng = new Rng(2024);
  private readonly panel: Panel;
  private readonly stats: HTMLDivElement;
  private readonly blurb: HTMLDivElement;
  private fps = 60;
  private readonly frozen = new Map<Actor, number>();
  private heroReturnAt = -1;
  private readonly tmp = new Vector3();

  constructor(canvas: HTMLCanvasElement, ui: HTMLElement) {
    const mobile = /Android|iPhone|iPad|Mobile/i.test(navigator.userAgent) || Math.min(window.innerWidth, window.innerHeight) < 600;
    this.stage = new Stage({ canvas, mobile });
    this.particles = new ParticleSystem(mobile ? 6000 : 12000);
    this.stage.scene.add(this.particles.mesh);
    this.effects = new Effects(this.stage.scene, this.particles);
    this.effects.onKick = (k) => this.stage.kick(k);

    for (const recipe of ALL_RECIPES) {
      const crowd = new Crowd(recipe, recipe === HERO_RECIPES[0] ? 2 : 72);
      this.crowds.set(recipe.id, crowd);
      this.stage.scene.add(crowd.mesh);
    }

    this.hero = this.spawn(HERO_RECIPES[0]!, 0, 0);
    this.gallery.push(this.hero);
    MONSTER_RECIPES.forEach((recipe, i) => {
      const m = this.spawn(recipe, 0, 0);
      m.phaseOffset = i * 0.23;
      this.monsters.push(m);
      this.gallery.push(m);
    });
    this.layoutGallery();
    window.addEventListener('resize', () => {
      this.layoutGallery();
      this.setFocus(this.focus);
    });

    // UI
    const hud = el(ui, 'hud', '<div class="title">Falling Sky</div><div>Visual showcase, everything generated by code</div>');
    this.stats = el(hud, 'stats');
    el(ui, 'hint', 'Tap a character to focus it.<br>Tap the ground to see everyone.');
    this.blurb = el(ui, 'blurb');
    this.panel = new Panel(ui);
    this.panel.addRow({
      id: 'char',
      label: 'Character',
      radio: true,
      chips: [{ id: 'all', label: 'All' }, ...ALL_RECIPES.map((r) => ({ id: r.id, label: r.name }))],
      onPick: (id) => this.setFocus(id === 'all' ? -1 : ALL_RECIPES.findIndex((r) => r.id === id)),
    });
    this.panel.addRow({
      id: 'anim',
      label: 'Animation',
      chips: [
        { id: 'idle', label: 'Idle' },
        { id: 'walk', label: 'Walk' },
        { id: 'attack', label: 'Attack' },
        { id: 'cast', label: 'Cast' },
        { id: 'hit', label: 'Hit' },
        { id: 'die', label: 'Die' },
      ],
      onPick: (id) => this.playAnimation(id),
    });
    this.panel.addRow({
      id: 'spell',
      label: 'Spells',
      chips: [
        { id: 'fireball', label: 'Fireball', className: 'spell fire' },
        { id: 'nova', label: 'Frost Nova', className: 'spell frost' },
        { id: 'chain', label: 'Chain Lightning', className: 'spell bolt' },
        { id: 'meteor', label: 'Meteor', className: 'spell fire' },
      ],
      onPick: (id) => this.cast(id),
    });
    this.panel.addRow({
      id: 'toggle',
      label: 'Scene',
      chips: [
        { id: 'horde', label: `Horde ×${HORDE_SIZE}` },
        { id: 'turntable', label: 'Turntable' },
      ],
      onPick: (id) => {
        if (id === 'horde') this.setHorde(!this.hordeOn);
        if (id === 'turntable') {
          this.turntable = !this.turntable;
          this.panel.setToggled('toggle', 'turntable', this.turntable);
        }
      },
    });
    this.panel.setActive('char', 'all');
    this.setFocus(-1);

    canvas.addEventListener('pointerdown', (e) => this.onTap(e.clientX, e.clientY));
  }

  private spawn(recipe: CharacterRecipe, x: number, z: number): Actor {
    const crowd = this.crowds.get(recipe.id)!;
    const a = crowd.spawn();
    a.x = x;
    a.z = z;
    a.yaw = 0;
    a.play(Clip.Idle);
    a.phaseOffset = this.rng.next();
    return a;
  }

  private get portrait(): boolean {
    return window.innerHeight > window.innerWidth;
  }

  /**
   * Places the gallery on a diagonal line. Landscape screens get a shallow line
   * that reads as a row; portrait screens get a steep one so everyone fits.
   */
  private layoutGallery(): void {
    const angle = this.portrait ? 1.08 : 0.32;
    const dx = Math.cos(angle) * GALLERY_SPACING;
    const dz = -Math.sin(angle) * GALLERY_SPACING;
    const n = this.gallery.length;
    const cx = 1.5;
    const cz = this.portrait ? 0.8 : 0.4;
    this.gallery.forEach((a, i) => {
      const k = i - (n - 1) / 2;
      a.x = cx + dx * k;
      a.z = cz + dz * k;
    });
  }

  private galleryCentre(): Vector3 {
    const c = new Vector3();
    for (const a of this.gallery) c.add(this.tmp.set(a.x, 0, a.z));
    return c.divideScalar(this.gallery.length);
  }

  // ---------- Focus and camera ----------

  setFocus(index: number): void {
    this.focus = index;
    const recipe = ALL_RECIPES[index];
    this.panel.setActive('char', recipe ? recipe.id : 'all');
    if (!recipe) {
      const c = this.galleryCentre();
      // Sit the group above the button panel: nudge the look point toward the camera
      this.stage.lookTarget.set(c.x, 0.9, c.z + (this.portrait ? 2.6 : 0.9));
      this.stage.zoomTarget = (this.portrait ? 1.3 : 0.82) + (this.hordeOn ? 0.25 : 0);
      this.blurb.innerHTML = '';
      return;
    }
    const a = this.gallery[index]!;
    this.stage.lookTarget.set(a.x, recipe.height * 0.42 + (recipe.hover ? 0.4 : 0), a.z + (this.portrait ? 0.9 : 0.3));
    this.stage.zoomTarget = (0.36 + recipe.height * 0.06) * (this.portrait ? 1.25 : 1);
    this.blurb.innerHTML = `<b>${recipe.name}</b><br>${recipe.blurb}`;
  }

  private onTap(px: number, py: number): void {
    let best = -1;
    let bestD = 70 * 70;
    const w = window.innerWidth;
    const h = window.innerHeight;
    this.gallery.forEach((a, i) => {
      const recipe = ALL_RECIPES[i]!;
      this.tmp.set(a.x, recipe.height * 0.5, a.z).project(this.stage.camera);
      const sx = (this.tmp.x * 0.5 + 0.5) * w;
      const sy = (-this.tmp.y * 0.5 + 0.5) * h;
      const d = (sx - px) ** 2 + (sy - py) ** 2;
      if (d < bestD) {
        bestD = d;
        best = i;
      }
    });
    this.setFocus(best);
  }

  // ---------- Animations ----------

  playAnimation(id: string): void {
    const clip: ClipId | undefined = ({ idle: Clip.Idle, walk: Clip.Walk, attack: Clip.Attack, cast: Clip.Cast, hit: Clip.Hit, die: Clip.Die } as Record<string, ClipId>)[id];
    if (clip === undefined) return;
    const targets = this.focus >= 0 ? [this.gallery[this.focus]!] : this.gallery;
    for (const a of targets) {
      if (clip === Clip.Hit) this.hitActor(a);
      else if (clip === Clip.Die) this.killActor(a);
      else a.play(clip);
    }
  }

  private hitActor(a: Actor): void {
    a.hit();
    const r = a.crowd.recipe;
    this.effects.burst(a.x, r.height * 0.55, a.z, 10, 3, [0.9, 0.12, 0.08], 0.5, 0.12, { gravity: 9, up: 2, priority: 0.8 });
  }

  private killActor(a: Actor): void {
    if (a.clip === Clip.Die) return;
    a.die();
    const r = a.crowd.recipe;
    this.effects.burst(a.x, r.height * 0.5, a.z, 24, 3.5, [0.9, 0.12, 0.08], 0.7, 0.18, { gravity: 8, up: 2.5, priority: 0.8 });
    this.after(2.6, () => {
      if (a.clip !== Clip.Die) return;
      a.play(Clip.Idle);
      a.flash = 0.8;
      this.effects.burst(a.x, 0.3, a.z, 30, 2.5, [0.3, 0.7, 1.3], 0.8, 0.22, { drag: 2, up: 2.5, alpha: 0.7, priority: 0.5 });
    });
  }

  private after(seconds: number, fn: () => void): void {
    this.timers.push({ at: this.time + seconds, fn });
  }

  // ---------- Spells ----------

  private heroHand(): Vec3 {
    return [this.hero.x + Math.sin(this.hero.yaw) * 0.6, 1.9, this.hero.z + Math.cos(this.hero.yaw) * 0.6];
  }

  private faceMonsters(): void {
    const target = this.monsters[0]!;
    this.hero.yaw = Math.atan2(target.x - this.hero.x, target.z - this.hero.z);
    this.heroReturnAt = this.time + 1.6;
  }

  private nearestMonster(from: Vec3, exclude: Set<Actor>): Actor | null {
    let best: Actor | null = null;
    let bestD = Infinity;
    for (const m of this.monsters) {
      if (exclude.has(m) || m.clip === Clip.Die) continue;
      const d = (m.x - from[0]) ** 2 + (m.z - from[2]) ** 2;
      if (d < bestD) {
        bestD = d;
        best = m;
      }
    }
    return best;
  }

  cast(id: string): void {
    this.faceMonsters();
    this.hero.play(Clip.Cast);
    const hand = this.heroHand();
    if (id === 'fireball') {
      this.after(0.28, () => {
        const target = this.nearestMonster(hand, new Set()) ?? this.monsters[0]!;
        const th = target.crowd.recipe.height * 0.5;
        this.effects.fireball(hand, [target.x, th, target.z], (x, _y, z) => {
          for (const m of this.monsters) {
            const d = Math.hypot(m.x - x, m.z - z);
            if (d < 1.2) this.killActor(m);
            else if (d < 3) this.hitActor(m);
          }
        });
      });
    } else if (id === 'nova') {
      this.after(0.3, () => {
        const radius = 6;
        this.effects.frostNova(this.hero.x, 0, this.hero.z, radius);
        for (const m of this.monsters) {
          if (Math.hypot(m.x - this.hero.x, m.z - this.hero.z) < radius) {
            this.hitActor(m);
            this.frozen.set(m, this.time + 2.5);
          }
        }
      });
    } else if (id === 'chain') {
      this.after(0.25, () => {
        const points: Vec3[] = [hand];
        const visited = new Set<Actor>();
        let cursor = hand;
        for (let i = 0; i < 6; i++) {
          const next = this.nearestMonster(cursor, visited);
          if (!next) break;
          visited.add(next);
          const p: Vec3 = [next.x, next.crowd.recipe.height * 0.55, next.z];
          points.push(p);
          cursor = p;
          this.after(0.05 * i, () => this.hitActor(next));
        }
        this.effects.chainLightning(points);
      });
    } else if (id === 'meteor') {
      const target = this.monsters[2] ?? this.monsters[0]!;
      this.after(0.2, () => {
        this.effects.meteor([target.x, 0, target.z], (x, _y, z) => {
          for (const m of this.monsters) {
            const d = Math.hypot(m.x - x, m.z - z);
            if (d < 2.6) this.killActor(m);
            else if (d < 5) this.hitActor(m);
          }
        });
      });
    }
  }

  // ---------- Horde ----------

  setHorde(on: boolean): void {
    this.hordeOn = on;
    this.panel.setToggled('toggle', 'horde', on);
    if (!on) {
      for (const h of this.horde) {
        const crowd = h.actor.crowd;
        const idx = crowd.actors.indexOf(h.actor);
        if (idx >= 0) crowd.actors.splice(idx, 1);
      }
      this.horde.length = 0;
    } else {
      const c = new Color();
      for (let i = 0; i < HORDE_SIZE; i++) {
        const recipe = MONSTER_RECIPES[i % MONSTER_RECIPES.length]!;
        let x = 0;
        let z = 0;
        for (let tries = 0; tries < 20; tries++) {
          x = this.rng.range(-17, 21);
          z = this.rng.range(-6.5, 13);
          const onStage = Math.abs(z - 0.5) < 3.4 && x > -7 && x < 10;
          if (!onStage) break;
        }
        const a = this.spawn(recipe, x, z);
        a.play(Clip.Walk);
        a.scale = this.rng.range(0.82, 1.18);
        c.setHSL(this.rng.range(0, 1), this.rng.range(0.1, 0.4), this.rng.range(0.4, 0.62));
        a.tint.set(1, 1, 1).lerp(c, 0.55);
        this.horde.push({ actor: a, heading: this.rng.range(0, Math.PI * 2), speed: this.rng.range(0.9, 1.6) });
      }
    }
    this.setFocus(this.focus);
  }

  private updateHorde(dt: number): void {
    for (const h of this.horde) {
      const a = h.actor;
      h.heading += (this.rng.next() - 0.5) * dt * 2.5;
      // Steer away from the stage line and back toward the middle when far
      const onStage = Math.abs(a.z - 0.5) < 3.8 && a.x > -8 && a.x < 11;
      if (onStage) h.heading += (a.z > 0.5 ? 1 : -1) * dt * 6;
      if (Math.abs(a.x - 2) > 19 || a.z < -7 || a.z > 14) {
        const toCentre = Math.atan2(2 - a.x, 4 - a.z);
        h.heading += Math.sign(Math.sin(toCentre - h.heading)) * dt * 4;
      }
      a.yaw = h.heading;
      a.x += Math.sin(h.heading) * h.speed * a.scale * dt;
      a.z += Math.cos(h.heading) * h.speed * a.scale * dt;
    }
  }

  // ---------- Frame ----------

  update(dt: number, render = true): void {
    this.time += dt;
    this.fps += (1 / Math.max(dt, 1e-3) - this.fps) * 0.05;

    for (let i = this.timers.length - 1; i >= 0; i--) {
      const t = this.timers[i]!;
      if (this.time >= t.at) {
        this.timers.splice(i, 1);
        t.fn();
      }
    }

    if (this.heroReturnAt > 0 && this.time > this.heroReturnAt) {
      this.heroReturnAt = -1;
    }
    if (this.heroReturnAt < 0 && this.hero.clip !== Clip.Cast) {
      // Ease back to facing the camera
      const diff = Math.atan2(Math.sin(-this.hero.yaw), Math.cos(-this.hero.yaw));
      this.hero.yaw += diff * Math.min(1, dt * 5);
    }

    if (this.turntable && this.focus >= 0) {
      const a = this.gallery[this.focus]!;
      if (a !== this.hero || this.heroReturnAt < 0) a.yaw += dt * 0.9;
    }

    for (const [a, until] of this.frozen) {
      if (this.time > until) {
        a.tint.set(1, 1, 1);
        this.frozen.delete(a);
      } else {
        a.tint.setRGB(0.55, 0.8, 1.35);
      }
    }

    // Sparkle from the sorcerer's crystal while idle
    if (this.hero.clip === Clip.Idle && this.rng.next() < dt * 6) {
      const h = this.heroHand();
      this.effects.burst(h[0] - Math.sin(this.hero.yaw) * 0.1, 2.25, h[2], 1, 0.4, [0.4, 1.1, 1.8], 0.9, 0.09, { up: 0.5, priority: 0.5 });
    }
    // Embers drifting from the braziers
    for (const t of this.stage.torchPositions) {
      if (this.rng.next() < dt * 10) {
        this.effects.burst(t.x, t.y - 0.35, t.z, 1, 0.5, [2, 0.8, 0.2], 1.4, 0.07, { up: 1.2, drag: 0.5, priority: 0.4 });
      }
    }

    this.updateHorde(dt);
    for (const crowd of this.crowds.values()) crowd.update(dt, this.time);
    this.effects.update(dt, this.stage.camera);
    this.stage.heroLight.position.set(this.hero.x, 1.7, this.hero.z + 0.4);
    this.stage.update(dt, this.time);
    this.particles.update(this.time, this.stage.camera);
    if (render) this.stage.render();

    if ((Math.floor(this.time * 4) & 1) === 0) {
      this.stats.textContent =
        `${this.fps.toFixed(0)} fps  ${(1000 / Math.max(this.fps, 1)).toFixed(1)} ms\n` +
        `scale ${this.stage.renderScale.toFixed(1)}  draws ${this.stage.drawCalls}\n` +
        `characters ${this.gallery.length + this.horde.length}`;
    }
  }
}
