/**
 * Vite plugin: makes the game installable to a phone's home screen without any
 * committed image files. Icons are drawn per pixel here at build time, the
 * manifest and a small service worker are emitted next to the bundle.
 */
import { deflateSync } from 'node:zlib';
import type { Plugin } from 'vite';

// ---------------------------------------------------------------- PNG encoder

const CRC_TABLE = new Uint32Array(256).map((_, n) => {
  let c = n;
  for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  return c >>> 0;
});

function crc32(buf: Uint8Array): number {
  let c = 0xffffffff;
  for (let i = 0; i < buf.length; i++) c = CRC_TABLE[(c ^ buf[i]!) & 0xff]! ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function chunk(type: string, data: Uint8Array): Uint8Array {
  const out = new Uint8Array(12 + data.length);
  const dv = new DataView(out.buffer);
  dv.setUint32(0, data.length);
  out.set([type.charCodeAt(0), type.charCodeAt(1), type.charCodeAt(2), type.charCodeAt(3)], 4);
  out.set(data, 8);
  dv.setUint32(8 + data.length, crc32(out.subarray(4, 8 + data.length)));
  return out;
}

function encodePng(size: number, rgba: Uint8Array): Uint8Array {
  const raw = new Uint8Array((size * 4 + 1) * size);
  for (let y = 0; y < size; y++) {
    raw[y * (size * 4 + 1)] = 0;
    raw.set(rgba.subarray(y * size * 4, (y + 1) * size * 4), y * (size * 4 + 1) + 1);
  }
  const ihdr = new Uint8Array(13);
  const dv = new DataView(ihdr.buffer);
  dv.setUint32(0, size);
  dv.setUint32(4, size);
  ihdr.set([8, 6, 0, 0, 0], 8);
  const sig = new Uint8Array([137, 80, 78, 71, 13, 10, 26, 10]);
  const parts = [sig, chunk('IHDR', ihdr), chunk('IDAT', new Uint8Array(deflateSync(raw))), chunk('IEND', new Uint8Array(0))];
  const total = parts.reduce((n, p) => n + p.length, 0);
  const out = new Uint8Array(total);
  let o = 0;
  for (const p of parts) {
    out.set(p, o);
    o += p.length;
  }
  return out;
}

// ---------------------------------------------------------------- the icon

/** A dark rounded square with a golden star falling across it, trailing light. */
function drawIcon(size: number, maskable: boolean): Uint8Array {
  const px = new Uint8Array(size * size * 4);
  const pad = maskable ? 0 : size * 0.04;
  const radius = maskable ? 0 : size * 0.22;
  const inner = maskable ? 0.8 : 1;
  const cx = size * 0.62;
  const cy = size * 0.4;
  const tailLen = size * 0.62 * inner;
  const dirX = -0.62;
  const dirY = 0.78;
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const i = (y * size + x) * 4;
      // Rounded-square mask
      const qx = Math.max(0, Math.abs(x + 0.5 - size / 2) - (size / 2 - pad - radius));
      const qy = Math.max(0, Math.abs(y + 0.5 - size / 2) - (size / 2 - pad - radius));
      const outside = Math.hypot(qx, qy) - radius;
      const alpha = maskable ? 1 : Math.max(0, Math.min(1, 0.5 - outside));
      if (alpha <= 0) continue;
      // Night sky gradient
      const t = y / size;
      let r = 8 + 18 * (1 - t);
      let g = 10 + 24 * (1 - t);
      let b = 22 + 44 * (1 - t);
      // Ground band
      if (t > 0.82) {
        r = 30;
        g = 28;
        b = 34;
      }
      // Star tail: distance to the segment from the head backwards
      const rx = x + 0.5 - cx;
      const ry = y + 0.5 - cy;
      const along = -(rx * dirX + ry * dirY); // positive behind the head
      const perp = Math.abs(rx * dirY - ry * dirX);
      if (along > 0 && along < tailLen) {
        const k = 1 - along / tailLen;
        const width = size * (0.02 + 0.06 * k);
        const glow = Math.max(0, 1 - perp / width) * k;
        r += 250 * glow;
        g += 200 * glow;
        b += 90 * glow;
      }
      // Star head
      const d = Math.hypot(rx, ry) / (size * 0.11);
      const head = Math.max(0, 1 - d * d);
      r += 255 * head;
      g += 235 * head;
      b += 160 * head;
      const halo = Math.max(0, 1 - Math.hypot(rx, ry) / (size * 0.3));
      r += 80 * halo * halo;
      g += 60 * halo * halo;
      b += 20 * halo * halo;
      px[i] = Math.min(255, r);
      px[i + 1] = Math.min(255, g);
      px[i + 2] = Math.min(255, b);
      px[i + 3] = Math.round(alpha * 255);
    }
  }
  return px;
}

const ICONS: { name: string; size: number; maskable: boolean }[] = [
  { name: 'icon-192.png', size: 192, maskable: false },
  { name: 'icon-512.png', size: 512, maskable: false },
  { name: 'icon-maskable-512.png', size: 512, maskable: true },
  { name: 'apple-touch-icon.png', size: 180, maskable: true },
];

function manifest(base: string): string {
  return JSON.stringify(
    {
      name: 'Falling Sky',
      short_name: 'Falling Sky',
      description: 'A grim action RPG for the browser. All art generated by code.',
      start_url: base,
      scope: base,
      display: 'fullscreen',
      orientation: 'any',
      background_color: '#06070c',
      theme_color: '#06070c',
      icons: [
        { src: `${base}icons/icon-192.png`, sizes: '192x192', type: 'image/png' },
        { src: `${base}icons/icon-512.png`, sizes: '512x512', type: 'image/png' },
        { src: `${base}icons/icon-maskable-512.png`, sizes: '512x512', type: 'image/png', purpose: 'maskable' },
      ],
    },
    null,
    2,
  );
}

function serviceWorker(base: string, assets: string[], version: string): string {
  return `// Falling Sky service worker, generated at build time
const CACHE = 'falling-sky-${version}';
const BASE = ${JSON.stringify(base)};
const ASSETS = ${JSON.stringify(assets)};
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  if (url.origin !== location.origin) return;
  if (e.request.mode === 'navigate') {
    // Always try for the newest page, fall back to the cached one offline
    e.respondWith(fetch(e.request).then((r) => { const copy = r.clone(); caches.open(CACHE).then((c) => c.put(BASE, copy)); return r; }).catch(() => caches.match(BASE)));
    return;
  }
  e.respondWith(caches.match(e.request).then((hit) => hit || fetch(e.request).then((r) => { if (r.ok && url.pathname.startsWith(BASE)) { const copy = r.clone(); caches.open(CACHE).then((c) => c.put(e.request, copy)); } return r; })));
});
`;
}

export function pwaPlugin(): Plugin {
  let base = '/';
  const icons = new Map<string, Uint8Array>();
  const renderIcons = () => {
    if (icons.size) return;
    for (const ic of ICONS) icons.set(ic.name, encodePng(ic.size, drawIcon(ic.size, ic.maskable)));
  };
  return {
    name: 'falling-sky-pwa',
    configResolved(config) {
      base = config.base.endsWith('/') ? config.base : config.base + '/';
    },
    transformIndexHtml() {
      return [
        { tag: 'link', attrs: { rel: 'manifest', href: `${base}manifest.webmanifest` }, injectTo: 'head' },
        { tag: 'link', attrs: { rel: 'apple-touch-icon', href: `${base}icons/apple-touch-icon.png` }, injectTo: 'head' },
        { tag: 'link', attrs: { rel: 'icon', type: 'image/png', sizes: '192x192', href: `${base}icons/icon-192.png` }, injectTo: 'head' },
      ];
    },
    configureServer(server) {
      renderIcons();
      server.middlewares.use((req, res, next) => {
        const url = (req.url ?? '').split('?')[0]!;
        const rel = url.startsWith(base) ? url.slice(base.length) : url.replace(/^\//, '');
        if (rel === 'manifest.webmanifest') {
          res.setHeader('Content-Type', 'application/manifest+json');
          res.end(manifest(base));
          return;
        }
        if (rel.startsWith('icons/')) {
          const png = icons.get(rel.slice(6));
          if (png) {
            res.setHeader('Content-Type', 'image/png');
            res.end(Buffer.from(png));
            return;
          }
        }
        next();
      });
    },
    generateBundle(_opts, bundle) {
      renderIcons();
      for (const [name, png] of icons) this.emitFile({ type: 'asset', fileName: `icons/${name}`, source: png });
      this.emitFile({ type: 'asset', fileName: 'manifest.webmanifest', source: manifest(base) });
      const assets = Object.keys(bundle)
        .filter((f) => /\.(js|css)$/.test(f))
        .map((f) => base + f);
      const version = Math.random().toString(36).slice(2, 10);
      this.emitFile({ type: 'asset', fileName: 'sw.js', source: serviceWorker(base, [base, ...assets], version) });
    },
  };
}
